baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Frog.care'
googleAnalytics = "G-BSP2HHTEYT"
theme = 'hugo-book'
[params]
BookTheme = 'auto'
BookRepo = 'https://github.com/capoferro/frogcare'
